### ISSUE TITLE
Custom controls TextInputLayout

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUtils/material.avalonia#21]
Need text input layout as a custom control
![image](https://user-images.githubusercontent.com/33497292/68964141-aed21780-07e9-11ea-9130-05264485eb66.png)

**Comment by appleneko2001** [comment]
No need to create custom controls for this and filled one 

I did a lot work for those widgets. Now it looks like this

![](https://user-images.githubusercontent.com/38249047/103747856-9f91d700-5046-11eb-8a35-0b869afb3cdd.png)

![](https://user-images.githubusercontent.com/38249047/103748149-057e5e80-5047-11eb-9a9d-e49dba84ab87.png)

Placeholder are animated when focus to text field or lost focusing.

Unfortunately, I dont have any idea about placeholder clip border since I cant use GeometryGroup or CombinedGeometry. Maybe I will wait when AvaloniaUI are completely supported GeometryGroup / CombinedGeometry.

**Comment by SKProCH** [comment]
@appleneko2001 can you create a pull request to us back to the repository? You have done a lot of work
